name: Deploy Static Page to GitHub Pages üöÄ # Nom du workflow

on:
  push:
    branches:
      - main # D√©clencher le workflow √† chaque push sur la branche 'main'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest # Environnement pour ex√©cuter les √©tapes
    permissions:
      contents: read
      pages: write
      id-token: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        # T√©l√©charge votre code du d√©p√¥t

      - name: Setup Pages
        uses: actions/configure-pages@v5
        # Configure l'environnement pour le d√©ploiement GitHub Pages

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # Le dossier qui contient votre site statique
          # Comme votre fichier est √† la racine, nous sp√©cifions '.'
          path: '.'
          
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
        # D√©ploie l'artefact sur GitHub Pages
